### PR TITLE
Master branch should track v16.0

### PR DESCRIPTION
**Pull request by AArnott**
This bumps the version to 16.0, and readies the repo for a v15.8 branch, which I will push assuming this PR gets approved.

### CODE REVIEW

**Comment by dgriffen** [comment]
Any idea why the travis-ci build failed?

**Comment by AArnott** [comment]
@dgriffen Yes, the travis failure was a repro of #22

**Comment by AArnott** [comment]
@dgriffen re-running the travis build resolved the test failure, as I suspected since it's an intermittently failing test. Can you sign off?

**Comment by dgriffen** [comment]
I wanted to get Michael's opinion on this first. I'll see if he has time.

**Pull request merged**
